project:
  type: website
  output-dir: docs

website:
  title: "statistics-with-R"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: episodes.qmd
        text: "Episodes"
      - href: about.qmd
        text: "About Me"

format:
  html:
    theme: litera
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

